import Head from 'next/head'
import {useState} from 'react';
import styles from '../styles/Home.module.css'

export default function buscaFilmes({list}) {
    const [searchText, SetSearchText] = useState('');
    const [movieList, SetMovieList] = useState([]);

    const FazerAbusca = async ()=> {
       if (searchText!==""){
           const result = await fetch(`http://localhost:3000/api/search?q=${searchText}`);
           const json = await result.json();
           SetMovieList(json.list);
       } 
    }

  return (
    <div className={styles.container}>
      <Head>
        <title>Aprendendo Next!!!!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
           BUSCA 
        </h1>
        <input type="text" value={searchText} onChange={e=>SetSearchText(e.target.value)}/>
        <button onClick={FazerAbusca}>Buscar</button>
        <hr/>
        <ul>
            {movieList.map(item=>(
                <li>
                    <a href={`/movie/${item.id}`}>
                        <img src={`https://image.tmdb.org/t/p/original${item.poster_path}`}/>
                        {item.title}
                    </a>
                </li>
            ))}
        </ul>
        
      </main>      
    </div>
  )
}

