import Head from 'next/head'
import Link from 'next/link'
//import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home({list}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Aprendendo Next!!!!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
           Site 01: Manipulando APIs do TMDB 
        </h1>
        <Link href="/busca">Ir para página de Busca</Link>

        <ul>
            {list.map(item =>(
              <li>
                <a href={`/movie/${item.id}`}>
                   <img src={`https://image.tmdb.org/t/p/original${item.poster_path}`} width="150"/><br/>
                   {item.title}
                </a>
              </li>
            ))}
          </ul>  
          <Link href="/sobre">Sobre mim!!!</Link>
      </main>      
    </div>
  )
}

export async function getServerSideProps() {
  const resposta = await fetch('http://localhost:3000/api/trending');
  const json = await resposta.json();

  return{
    props: {
        list: json.list
    }
  };
}
